# Generated by Django 4.0.6 on 2022-12-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cust_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
