# Generated by Django 4.0.6 on 2022-12-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0003_alter_order_cust_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return1',
            name='cust1_phone',
            field=models.IntegerField(null=True),
        ),
    ]
