# Generated by Django 4.0.6 on 2022-12-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0004_alter_return1_cust1_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return1',
            name='cust1_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
