# Generated by Django 4.0.6 on 2022-12-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_1', '0006_alter_order_cust_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cust_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
